version: '3.8'

networks:
  vh-net:
    name: vh-net
    driver: bridge
    ipam:
      driver: default
      config: 
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.1

services:
  db:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: postgres
    # command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - "5432:5432"
    restart: always
    networks:
      vh-net:
        ipv4_address: 172.18.0.5
    user: postgres 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
  # backend:
  #   build:
  #     context: ./backend/
  #     dockerfile: ./backend/Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db
  #   networks:
  #     - default
  
  # Migrator:
  # Frontend:
volumes:
  db-data:

