version: '3.8'

networks:
  vh-net:
    name: vh-net
    driver: bridge
    ipam:
      driver: default
      config: 
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1

services:
  db:
    image: postgres
    container_name: pg-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    restart: always
    networks:
      - vh-net
    user: postgres 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    networks:
      - vh-net
    volumes:
      - ./backend/Migrations:/migrations
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c"]
    command: >
      'migrate -database "postgres://postgres:helloworld@db:5432/postgres?sslmode=disable" -path /migrations force 1 && yes | migrate -path /migrations -database "postgres://postgres:helloworld@db:5432/postgres?sslmode=disable" down &&
      migrate -path /migrations -database "postgres://postgres:helloworld@db:5432/postgres?sslmode=disable" up'

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - migrate
      - db
    networks:
      - vh-net

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - vh-net
    volumes:
      - /app/node_modules
      - ./frontend:/app



 
 
  # pgadmin:
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=vacaramin86@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=helloworld
  #   hostname: service-pgadmin
  #   ports:
  #     - '5555:80'
  #   image: dpage/pgadmin4
  #   volumes:
  #     - ./.data/pgadmin:/var/lib/pgadmin
  #   networks:
  #     vh-net:
  #       ipv4_address: 172.19.0.6
volumes:
  db-data: