version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
      
    depends_on:
      - db
volumes:
  db-data:
